CREATE TABLE USUARIO
(
    NOMBRE VARCHAR2(25) NOT NULL UNIQUE,
    PARTIDAS_JUGADAS NUMBER DEFAULT 0,
    PARTIDAS_GANADAS NUMBER DEFAULT 0,
    PARTIDAS_PERDIDAS NUMBER DEFAULT 0,
    CONSTRAINT USUARIO_PK PRIMARY KEY (NOMBRE)
);

CREATE TABLE TABLERO
(
    ID NUMBER NOT NULL,
    JUGADOR_1 VARCHAR2(25) NOT NULL,
    JUGADOR_2 VARCHAR2(25) NOT NULL,
    PUNTAJE_JG_1 NUMBER DEFAULT 0,
    PUNTAJE_JG_2 NUMBER DEFAULT 0,
    CONSTRAINT TABLERO_PK PRIMARY KEY (ID),
    CONSTRAINT JUGADOR1_FK FOREIGN KEY (JUGADOR1) REFERENCES USUARIO,
    CONSTRAINT JUGADOR2_FK FOREIGN KEY (JUGADOR2) REFERENCES USUARIO
);

CREATE TABLE CASILLA
(
    X NUMBER(2) NOT NULL,
    Y NUMBER(2) NOT NULL,
    BONUS NUMBER(1),
    LETRA VARCHAR2(1),
    ID_TABLERO NUMBER NOT NULL,
    CONSTRAINT CASILLA_PK PRIMARY KEY (X, Y, ID_TABLERO),
    CONSTRAINT ID_TABLERO_FK FOREIGN KEY (ID_TABLERO) REFERENCES TABLERO
);

CREATE TABLE LETRA
(
    ID VARCHAR2(2) NOT NULL,
    PUNTAJE NUMBER NOT NULL,
    CONSTRAINT LETRA_PK PRIMARY KEY (ID)
);

CREATE TABLE LETRAS_TABLERO
(
    ID_LETRA VARCHAR2(1) NOT NULL,
    ID_TABLERO NUMBER NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    CONSTRAINT LETRAS_TABLERO_PK PRIMARY KEY (ID_LETRA, ID_TABLERO)
);

CREATE TABLE LETRAS_USUARIO_TABLERO
(
    ID_USUARIO VARCHAR2(25) NOT NULL,
    ID_TABLERO NUMBER NOT NULL,
    ID_LETRA VARCHAR2(1) NOT NULL,
    CONSTRAINT LETRAS_USUARIO_TABLERO_PK PRIMARY KEY (ID_USUARIO, ID_TABLERO, ID_LETRA),
    CONSTRAINT ID_USUARIO_FK FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO,
    CONSTRAINT ID_TABLERO_USUARIO_FK FOREIGN KEY (ID_TABLERO) REFERENCES TABLERO,
    CONSTRAINT ID_LETRA_USUARIO_FK FOREIGN KEY (ID_LETRA) REFERENCES LETRA
);

CREATE TABLE LST_VALORES
(
    CODIGO VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    VALOR NUMBER NOT NULL,
    CONSTRAINT LST_VALORES_PK PRIMARY KEY (CODIGO, NOMBRE)
);

CREATE TABLE PALABRA
(
  ID NUMBER NOT NULL,
  PALABRA VARCHAR2(25) NOT NULL,
  CONSTRAINT PALABRAS_PK PRIMARY KEY (ID)
);