CREATE TABLE USUARIO
(
    NOMBRE VARCHAR2(25) NOT NULL UNIQUE,
    PARTIDAS_JUGADAS NUMBER DEFAULT 0,
    PARTIDAS_GANADAS NUMBER DEFAULT 0,
    PARTIDAS_PERDIDAS NUMBER DEFAULT 0,
    CONSTRAINT USUARIO_PK PRIMARY KEY (NOMBRE)
);

CREATE TABLE TABLERO
(
    ID NUMBER NOT NULL,
    JUGADOR1 VARCHAR2(25) NOT NULL,
    JUGADOR2 VARCHAR2(25) NOT NULL,
    CONSTRAINT TABLERO_PK PRIMARY KEY (ID),
    CONSTRAINT JUGADOR1_FK FOREIGN KEY (JUGADOR1) REFERENCES USUARIO,
    CONSTRAINT JUGADOR2_FK FOREIGN KEY (JUGADOR2) REFERENCES USUARIO
);

CREATE TABLE CASILLA
(
    X NUMBER(2) NOT NULL,
    Y NUMBER(2) NOT NULL,
    BONUS NUMBER(1) NOT NULL,
    LETRA VARCHAR2(1) NOT NULL,
    ID_TABLERO NUMBER NOT NULL,
    CONSTRAINT CASILLA_PK PRIMARY KEY (X, Y),
    CONSTRAINT ID_TABLERO_FK FOREIGN KEY (ID_TABLERO) REFERENCES TABLERO
);

CREATE TABLE LETRA
(
    ID VARCHAR2(1) NOT NULL,
    PUNTAJE NUMBER NOT NULL,
    CONSTRAINT LETRA_PK PRIMARY KEY (ID)
);

CREATE TABLE LETRAS_TABLERO
(
    ID_LETRA VARCHAR2(1) NOT NULL,
    ID_TABLERO NUMBER NOT NULL,
    CANTIDAD_DISPONIBLE NUMBER NOT NULL,
    CONSTRAINT LETRAS_TABLERO_PK PRIMARY KEY (ID_LETRA, ID_TABLERO)
);

CREATE TABLE LST_VALORES
(
    CODIGO VARCHAR2(50) NOT NULL,
    NOMBRE VARCHAR2(50) NOT NULL,
    VALOR NUMBER NOT NULL,
    CONSTRAINT LST_VALORES_PK PRIMARY KEY (CODIGO, NOMBRE)
);

CREATE TABLE PALABRA
(
  ID NUMBER NOT NULL,
  PALABRA VARCHAR2(25) NOT NULL,
  CONSTRAINT PALABRAS_PK PRIMARY KEY (ID)
);