INSERT ALL
    --Lista de letras
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'A', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'B', 3)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'C', 3)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'D', 2)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'E', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'F', 4)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'G', 2)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'H', 4)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'I', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'J', 8)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'K', 5)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'L', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'M', 3)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'N', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'Ñ', 8)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'O', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'P', 3)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'Q', 5)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'R', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'S', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'T', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'U', 1)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'V', 4)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'W', 4)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'X', 8)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'Y', 4)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_LETRAS', 'Z', 10)

    --Lista de bonus de palabra
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_BONUS_PALABRA', 'DP', 2)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_BONUS_PALABRA', 'TP', 3)

    --Lista de bonus de letras
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_BONUS_LETRA', 'DL', 2)
    INTO LST_VALORES (CODIGO, NOMBRE, VALOR) VALUES ('LST_BONUS_LETRA', 'TL', 3)
SELECT 1 FROM DUAL;